baseURL = "https://financegate.xyz"
googleAnalytics = ""
theme = "omega"
title = "FinanceGate"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Products"
pre = "#"
url = "products"
weight = 3
[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 5
[params]
author = "Themefisher"
contact_info = "Pariser Platz<br>10117 Berlin, <br>Germany"
description = "This is meta description"
logo = "/images/logo-1.png"
logo_width = "190px"
preloader = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "52.4811096"
map_center_lng = "12.8498906"
map_marker = "images/map-marker.png"
map_position_lat = "52.5164270"
map_position_lng = "13.3778211"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/financegateDAO"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/financegatedao/"
title = "instagram"
